name: deploy

on:
  # 支持手动触发构建
  workflow_dispatch:
  release:
    # 创建release的时候触发
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 发布到maven仓库
      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.39
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"

#          ssh-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

          git-release-bot-name: "codeleep-bot"
          git-release-bot-email: "codeleep@163.com"

          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GIT_GPG_KEY_ID }}
          gpg-key: ${{ secrets.GIT_GPG_KEY }}


