name: deploy

on:
  # 支持手动触发构建
  workflow_dispatch:
  release:
    # 创建release的时候触发
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取源码
      - uses: actions/checkout@v2
      # 安装JDK环境
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # 设置Maven中央仓库配置
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: releases
          # Nexus用户名环境变量
          server-username: OSSRH_USERNAME
          # Nexus密码环境变量
          server-password: OSSRH_PASSWORD
          # gpg短密码环境变量
          gpg-passphrase: OSSRH_GPG_SECRET_KEY
          # gpg私钥
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      # 推送jar包至maven中央仓库
      - name: Publish to Apache Maven Central
        # 执行maven deploy命令
        run: mvn clean deploy
        # 环境变量设置
        env:
          # Nexus用户名,如果觉得不想暴露也可以配置到secrets中
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          # Nexus密码
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_PASSWORD }}
          # gpg短密码
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      # Nexus自动部署
      - name: Release on nexus
        uses: monkeyWie/maven-nexus-release@v1
        with:
          # Nexus用户名
          maven-repo-server-username: ${{ secrets.OSSRH_USERNAME }}
          # Nexus密码
          maven-repo-server-password: ${{ secrets.OSSRH_PASSWORD }}
